DrSLMac/pantry-to-pan

- dist/index.html
- src/styles.css
Wrote basic css to block out wireframe for visibility.
> Write basic css to block wireframe

- src/classes/Recipe.js
- test/Recipe-test.js
- Adds testing for Recipe class
- line: 1-117
- Unskip one by one
- Make sure following instructions on prompts
> Recipe tests

- test/RecipeRepository-test.js
-Adds testing for Recipe Repository Class
-At the beginning
- Unskip tests one by one
> Recipe repository/test

- src/classes/RecipeRepository.js
- test/RecipeRepository-test.js
-Creates RecipeRepository Class
-Takes data (cookbook) as argument
-Stores data in an array
-Can filter data based on tags
-Can filter data based on name
Line 0
One test at a time
> Recipe repository class

- src/classes/User-class.js
- test/User-test.js
Dinne and I wrote the user tests and class, but have not yet done the method recipesToCook.
> Build User class and test

- dist/index.html
- src/styles.css
Hi team! I made a skeleton for the filter screen for when they select their button/option from the main screen.
#Pull Request
#Checklist:
> Create filter screen

- dist/index.html
- src/scripts.js
- src/styles.css
Hi, team. I built a wireframe for the actual recipe when the user clicks to show it.
#Pull Request
- [ X] New feature (adds functionality)
- [ X] I tested my changes in the browser
#Checklist:
- [ X] My code follows the style guidelines of this project
- [ X] My changes generate no new bugs
> Build recipe page with side for ingredient list

- src/scripts.js
- test/RecipeRepository-test.js
> Add imports

- src/scripts.js
This is untested, as the data is not populating yet, but I've written a function that should add the saved recipes for the toCook user story.
#Pull Request
#Checklist:
> Write function to add to saved

- src/data/ingredients.js
- src/data/users.js
- src/scripts.js
> import data to scripts.js

- src/classes/User-class.js
- test/User-test.js
> Add User and User-test

- src/classes/RecipeRepository.js
- src/scripts.js
- test/RecipeRepository-test.js
> Call RecipeRepository Methods

- dist/index.html
- src/classes/RecipeRepository.js
- src/scripts.js
> Make homepage load

- dist/index.html
- src/classes/RecipeRepository.js
- src/scripts.js
> Show images on front page

- src/scripts.js
> Get recipe data to populate on all recipes

- src/scripts.js
> Add recipe directions

- src/scripts.js
> Add function for displaying recipe instructions

- dist/index.html
- src/scripts.js
- src/styles.css
I've updated the css and html to correct the grid items to be cards.
#Pull Request
#Checklist:
> Assign grid items to be cards

- dist/index.html
- src/classes/Recipe.js
- src/classes/RecipeRepository.js
- src/scripts.js
- test/Recipe-test.js
- test/RecipeRepository-test.js
> Add Recipe view, fix calculate total, refactory-test.js

- src/classes/Recipe.js
- src/scripts.js
- test/Recipe-test.js
> Add recipe direction page and recipe tests

- src/classes/Recipe.js
- src/scripts.js
- test/Recipe-test.js
> Refactor recipe

- dist/index.html
- src/scripts.js
- src/styles.css
> css styling edits

- dist/index.html
- src/scripts.js
> Add HTML refactor/fix

- dist/index.html
- src/scripts.js
> Add Saved Recipe Page

- dist/index.html
- src/classes/User-class.js
- src/scripts.js
There is functionality, but there are bugs when adding recipe. Full recipe page still showing when we go out of view recipe view.
#Pull Request
#Checklist:
> Create functionality to add saved recipe to array and visible on website

- src/scripts.js
Clean up code and recipe adds to saved grid
#Pull Request
#Checklist:
> Add functions for favorite recipe

- src/apiCalls.js
- src/classes/Recipe.js
- src/scripts.js
> brought in api info

- dist/index.html
- src/classes/Recipe.js
- src/classes/RecipeRepository.js
- src/scripts.js
> Refactor scripts, recipes, html, resipesRepo

- src/scripts.js
> Repopulate allRecipes page if checkbox values are allunchecked

- src/scripts.js
#Pull Request
resolved view recipe page showing when favorite button is pushed
added button and favorite functionality to filtered recipes
#Checklist:
> fixed view recipe page

- dist/index.html
- src/scripts.js
- src/styles.css
#Pull Request
Completes the functionality of "Remove" button
#Checklist:
> add functionality remove function

- src/scripts.js
- src/styles.css
#Pull Request
added favorite button to recipe page
#Checklist:
> add button to recipe page

- src/apiCalls.js
- src/scripts.js
Wrote frame for POST. We will need to update the values in the function once we complete the pantry class.
#Pull Request
#Checklist:
> Build frame for POST

- dist/index.html
- src/apiCalls.js
- src/classes/Pantry.js
- src/classes/RecipeRepository.js
- src/classes/User-class.js
- src/scripts.js
#Pull Request
#Checklist:
- Recipes can be viewed, recipe instructions can be seen,  recipes can be saved and delete, fetch calls work with the local api, We need to complete the data for the POST and add in the datasets.
> feat Fetch and post, data pulling

- dist/index.html
> Add language and direction

- dist/index.html
> Update checkboxes for screen reader

- src/classes/Recipe.js
- src/classes/RecipeRepository.js
- src/scripts.js
Code broke with merge - unmerging
Reverts DrSLMac/pantry-to-pan#104
> Revert "Feat/refactorapi"

- dist/index.html
- src/classes/Recipe.js
- src/scripts.js
> fixed viewAllRecipes with current methods
